title: Shourya Sharma 
logo: /assets/img/photo.jpg
description: Cybersecurity professional with a Bachelor's in Computer Science and Engineering, specializing in Cybersecurity. Certified in CEH v13, with hands-on experience in ethical hacking and IT infrastructure. Proficient in Python, C, C++, Shell scripting, and various operating systems (Windows, macOS, Linux). Connect with me on LinkedIn or via email at sharmashorya498@gmail.com.
show downloads: false
theme: Jekyll-theme-minimal
